### PR TITLE
update Expressions to V2 contract with express_as_citizenship

### PR DESCRIPTION
**Pull request by streamerd**
adapted dapp to EoPV2 on Görli testnet, implemented like this, screenshots are from localhost. Please review and if you like it, approve pull request. 

used this lib for selector:     "react-flags-select": "^2.2.3" and "country-flag-icons": "^1.5.5" for displaying the flags on last expression ( expressed by someone from ... (countryFlag in Unicode)).

https://www.npmjs.com/package/react-flags-select

the arrow opening the dropdown/search menu needs to be clicked well and its size seems not adjustable. , other than that it's quite snappy and functioning as expected ;)

https://www.npmjs.com/package/country-dropdown-with-flags-for-react

Here are some concerns about conditions where the icons will not appear well for some countries (eg. Canada) in older version operating systems/ browsers.
https://esham.io/2014/06/unicode-flags

~ we need to change that in the future, and make both as part of improvement/enhancement planning.

afterall, below is the tx that including data on screenshots below. click on view more, then show input data/decode and see what data passed to the v2 contract, via the dapp. (ISO codes for country info, eg. TR for Turkey (Changed to Türkiye now)).

https://goerli.etherscan.io/tx/0x98072f70d155eb8d1d39a2ed1034711174ccd48fe6d10f427b3550604f485a37

Search and select citizenship info
Search and select citizenship info
Search and select citizenship info
Display citizenship info after selection
Display citizenship info after selection
Read citizenship info @ last expression
Read citizenship info @ last expression

### CODE REVIEW

**Comment by docxology** [comment]
Can people select only 1 citizenship, or more? 

Thanks for the review request, I have to say that at this time I am not familiar enough with the technical aspects to be too useful.

**Comment by streamerd** [comment]
> Can people select only 1 citizenship, or more?
> 

for now, it is only 1 to select from, but in reality we can have multiple of course, and that'd be well reflected as an improvement to this ;) I would be grateful if you'd open a feature request/ issue ticket here marked as enhancement, or I'd do it soon.

> Thanks for the review request, I have to say that at this time I am not familiar enough with the technical aspects to be too useful.

and well, Daniel, all feedback is appreciated, and the aspect you've mentioned better be included in the next iterations, it's got highly relative and overlapping parts with the incentive mechanisms, when we get Acknowledgements of Peace deployed & launched as well. 

Would be great to imagine that part as well, that's gonna be the point we'll start observing p2p diplomacy in action ~ 

_+ also looking for a designer for reviewing the interaction/experience aspect. will probably merge before that happens but all will evolve in time._

**Review by docxology — APPROVED** [review]
Thank you, looks good from me.

**Review by decisiveHoneyBadger — APPROVED** [review]
despite some minor UI-issues it is good to go

**Comment by withinthevacuum** [comment]
I've just test it with the country selection and it works very well.

**Pull request merged**
